### ISSUE TITLE
Cant get attribute "charge_point_id" to work?

### ISSUE THREAD

**Issue by LarsFransson65** [kirei/hass-chargeamps#49]
I have 2 Halo chargers and I want to load balance them with an automation setting the attibute "max_current".
I can get this working on one of the chargers by using this command:
- - - 
action:
  - service: chargeamps.set_max_current
    metadata: {}
    data:
      connector: 1
      max_current: 10
- - - 

However, when trying to add charge_point_id, its not working?
- - -
action:
  - service: chargeamps.set_max_current
    metadata: {}
    data:
      charge_point_id: 190xxxxxM
      connector: 1
      max_current: 10
- - -

Can you please advice on this?
Best regards
Lasse

**Comment by fredriklj** [comment]
@LarsFransson65, where did you get "charge_point_id" from? The parameter name you are looking for is "chargepoint", I guess?

**Comment by LarsFransson65** [comment]
I got it from the integration documentation…
Tried chargepoint but it did not work.
I have three Halo changers but I can only change set_max_current on one, the first changer. I need to be able to set it on all chargers.

[image0.jpeg]

Skickat från min iPad

23 feb. 2024 kl. 10:45 skrev Fredrik Ljunggren ***@***.***>:

﻿

@LarsFransson65<https://github.com/LarsFransson65>, where did you get "charge_point_id" from? The parameter name you are looking for is "chargepoint", I guess?

**Comment by jschlyter** [comment]
Example from one of my setups:

```
automation:
  - alias: evcc_set_max_current
    id: 11AAB299-65F5-4AFF-969C-38E24AF67E9B
    trigger:
      - platform: state
        entity_id: input_number.evcc_max_current
    action:
      - service: chargeamps.set_max_current
        data_template:
          chargepoint: 2002009999X
          connector: 1
          max_current: "{{ states('input_number.evcc_max_current') | int }}"```
```
